In [2]:
import numpy as np
np.transpose

In [13]:
arr = np.arange(120).reshape((2, 3, 4, 5))

print(
    np.apply_along_axis(lambda arr: np.array([[*arr, 0, 1]] * 2), axis=1, arr=arr).shape
)
print(np.apply_along_axis(lambda arr: [np.sum(arr)], axis=1, arr=arr).shape)

(2, 2, 5, 4, 5)
(2, 1, 4, 5)


In [14]:
print(np.arange(10)[-1:])


np.ones((2,3,4,))

[9]


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [10]:
print(np.arange(15000).reshape(20, 5,-1))

np.ndarray.__repr__


[[[    0     1     2 ...   147   148   149]
  [  150   151   152 ...   297   298   299]
  [  300   301   302 ...   447   448   449]
  [  450   451   452 ...   597   598   599]
  [  600   601   602 ...   747   748   749]]

 [[  750   751   752 ...   897   898   899]
  [  900   901   902 ...  1047  1048  1049]
  [ 1050  1051  1052 ...  1197  1198  1199]
  [ 1200  1201  1202 ...  1347  1348  1349]
  [ 1350  1351  1352 ...  1497  1498  1499]]

 [[ 1500  1501  1502 ...  1647  1648  1649]
  [ 1650  1651  1652 ...  1797  1798  1799]
  [ 1800  1801  1802 ...  1947  1948  1949]
  [ 1950  1951  1952 ...  2097  2098  2099]
  [ 2100  2101  2102 ...  2247  2248  2249]]

 ...

 [[12750 12751 12752 ... 12897 12898 12899]
  [12900 12901 12902 ... 13047 13048 13049]
  [13050 13051 13052 ... 13197 13198 13199]
  [13200 13201 13202 ... 13347 13348 13349]
  [13350 13351 13352 ... 13497 13498 13499]]

 [[13500 13501 13502 ... 13647 13648 13649]
  [13650 13651 13652 ... 13797 13798 13799]
  [13800 13801 138

<slot wrapper '__repr__' of 'numpy.ndarray' objects>

In [13]:
print(np.arange(15000).reshape(20, 5,-1, 1))


[[[[    0]
   [    1]
   [    2]
   ...
   [  147]
   [  148]
   [  149]]

  [[  150]
   [  151]
   [  152]
   ...
   [  297]
   [  298]
   [  299]]

  [[  300]
   [  301]
   [  302]
   ...
   [  447]
   [  448]
   [  449]]

  [[  450]
   [  451]
   [  452]
   ...
   [  597]
   [  598]
   [  599]]

  [[  600]
   [  601]
   [  602]
   ...
   [  747]
   [  748]
   [  749]]]


 [[[  750]
   [  751]
   [  752]
   ...
   [  897]
   [  898]
   [  899]]

  [[  900]
   [  901]
   [  902]
   ...
   [ 1047]
   [ 1048]
   [ 1049]]

  [[ 1050]
   [ 1051]
   [ 1052]
   ...
   [ 1197]
   [ 1198]
   [ 1199]]

  [[ 1200]
   [ 1201]
   [ 1202]
   ...
   [ 1347]
   [ 1348]
   [ 1349]]

  [[ 1350]
   [ 1351]
   [ 1352]
   ...
   [ 1497]
   [ 1498]
   [ 1499]]]


 [[[ 1500]
   [ 1501]
   [ 1502]
   ...
   [ 1647]
   [ 1648]
   [ 1649]]

  [[ 1650]
   [ 1651]
   [ 1652]
   ...
   [ 1797]
   [ 1798]
   [ 1799]]

  [[ 1800]
   [ 1801]
   [ 1802]
   ...
   [ 1947]
   [ 1948]
   [ 1949]]

  [[ 1950]
   [ 1951]

In [3]:
print(np.arange(120).reshape([2,3,4,5])[:,0,[1,2],None,:].shape)
print(np.arange(120).reshape([2,3,4,5])[:,0,[1,2],:].shape)

(2, 2, 1, 5)
(2, 2, 5)


In [4]:
print(np.arange(120).std())

34.63981331743384


In [5]:
np.where(np.arange(10)%2, np.arange(10), np.arange(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:

np.arange(120).reshape([-1, 3])[2:-3:6]

array([[ 6,  7,  8],
       [24, 25, 26],
       [42, 43, 44],
       [60, 61, 62],
       [78, 79, 80],
       [96, 97, 98]])

In [5]:
import numpy as np
import json
print(json.dumps(np.arange(120).reshape([-1,3]).tolist()), flush=True)

[[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11], [12, 13, 14], [15, 16, 17], [18, 19, 20], [21, 22, 23], [24, 25, 26], [27, 28, 29], [30, 31, 32], [33, 34, 35], [36, 37, 38], [39, 40, 41], [42, 43, 44], [45, 46, 47], [48, 49, 50], [51, 52, 53], [54, 55, 56], [57, 58, 59], [60, 61, 62], [63, 64, 65], [66, 67, 68], [69, 70, 71], [72, 73, 74], [75, 76, 77], [78, 79, 80], [81, 82, 83], [84, 85, 86], [87, 88, 89], [90, 91, 92], [93, 94, 95], [96, 97, 98], [99, 100, 101], [102, 103, 104], [105, 106, 107], [108, 109, 110], [111, 112, 113], [114, 115, 116], [117, 118, 119]]


In [ ]:
np.add
np.sort

In [6]:
np.array([[1,2],[1,2],[1,2]]).sum(axis=0, keepdims=np.nan)

TypeError: integer argument expected, got float

In [7]:
np.sum(np.ones(np.array([10,2])), axis=0, keepdims=True)

array([[10., 10.]])

In [8]:
np.ones(3, dtype = int) | np.ones(3, dtype = int) + np.ones(3)

TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [ ]:
np.arange(120).reshape([2,3,5,4])[0, np.ones((3, 5), dtype=bool), :-1].shape

In [11]:
10**3**2

1000000000

In [13]:
2**-0.5**2, 2**(-0.5**2) , (2**-0.5)**2 

(0.8408964152537145, 0.8408964152537145, 0.5000000000000001)

In [14]:
np.isclose(np.ones((4, 5)), np.ones((3)))

ValueError: operands could not be broadcast together with shapes (4,5) (3,) 

In [15]:
-1**2

-1

In [18]:
np.linspace(0,1,10, endpoint=True)
np.geomspace

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [21]:
~np.zeros((100,100), dtype=int)


array([[-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       ...,
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1]])

In [50]:
np.arange(120).reshape(2,3,4,5)[..., np.arange(12).reshape((3,4))<5, None, :]

array([[[[ 0,  1,  2,  3,  4]],

        [[ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14]],

        [[15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24]]],


       [[[60, 61, 62, 63, 64]],

        [[65, 66, 67, 68, 69]],

        [[70, 71, 72, 73, 74]],

        [[75, 76, 77, 78, 79]],

        [[80, 81, 82, 83, 84]]]])

In [48]:
np.arange(120).reshape(2,3,4,5)[..., np.arange(12).reshape((3,4))<5, None, :, ...].shape

IndexError: an index can only have a single ellipsis ('...')

In [49]:
np.arange(120).reshape(2,3,4,5)[..., 0,0,0,0]

array(0)

In [3]:
x = np.arange(12).reshape((3,4))
y = x[0:1:3, 1:3]
print(y.base)
y = x[..., 1:3]
print(y.base)

y = x[0, 1:3]
print(y.base)

y = x[np.ones_like(x, dtype=bool)]
print(y.base)

print(x.ravel().base)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
None
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
np.isclose