In [9]:
import numpy as np
# import pandas as pd

# x = np.linspace(-10,10,20)
# [*pd.cut(x, bins=5)]

[Interval(-10.02, -6.0, closed='right'),
 Interval(-10.02, -6.0, closed='right'),
 Interval(-10.02, -6.0, closed='right'),
 Interval(-10.02, -6.0, closed='right'),
 Interval(-6.0, -2.0, closed='right'),
 Interval(-6.0, -2.0, closed='right'),
 Interval(-6.0, -2.0, closed='right'),
 Interval(-6.0, -2.0, closed='right'),
 Interval(-2.0, 2.0, closed='right'),
 Interval(-2.0, 2.0, closed='right'),
 Interval(-2.0, 2.0, closed='right'),
 Interval(-2.0, 2.0, closed='right'),
 Interval(2.0, 6.0, closed='right'),
 Interval(2.0, 6.0, closed='right'),
 Interval(2.0, 6.0, closed='right'),
 Interval(2.0, 6.0, closed='right'),
 Interval(6.0, 10.0, closed='right'),
 Interval(6.0, 10.0, closed='right'),
 Interval(6.0, 10.0, closed='right'),
 Interval(6.0, 10.0, closed='right')]

In [3]:
print(np.arange(120).reshape([2,3,4,5])[:,0,[1,2],None,:].shape)
print(np.arange(120).reshape([2,3,4,5])[:,0,[1,2],:].shape)

(2, 2, 1, 5)
(2, 2, 5)


In [4]:
print(np.arange(120).std())

34.63981331743384


In [5]:
np.where(np.arange(10)%2, np.arange(10), np.arange(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:

np.arange(120).reshape([-1, 3])[2:-3:6]

array([[ 6,  7,  8],
       [24, 25, 26],
       [42, 43, 44],
       [60, 61, 62],
       [78, 79, 80],
       [96, 97, 98]])

In [5]:
import numpy as np
import json
print(json.dumps(np.arange(120).reshape([-1,3]).tolist()), flush=True)

[[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11], [12, 13, 14], [15, 16, 17], [18, 19, 20], [21, 22, 23], [24, 25, 26], [27, 28, 29], [30, 31, 32], [33, 34, 35], [36, 37, 38], [39, 40, 41], [42, 43, 44], [45, 46, 47], [48, 49, 50], [51, 52, 53], [54, 55, 56], [57, 58, 59], [60, 61, 62], [63, 64, 65], [66, 67, 68], [69, 70, 71], [72, 73, 74], [75, 76, 77], [78, 79, 80], [81, 82, 83], [84, 85, 86], [87, 88, 89], [90, 91, 92], [93, 94, 95], [96, 97, 98], [99, 100, 101], [102, 103, 104], [105, 106, 107], [108, 109, 110], [111, 112, 113], [114, 115, 116], [117, 118, 119]]


In [ ]:
np.add

In [6]:
np.array([[1,2],[1,2],[1,2]]).sum(axis=0, keepdims=np.nan)

TypeError: integer argument expected, got float

In [7]:
np.sum(np.ones(np.array([10,2])), axis=0, keepdims=True)

array([[10., 10.]])

In [8]:
np.ones(3, dtype = int) | np.ones(3, dtype = int) + np.ones(3)

TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [ ]:
np.arange(120).reshape([2,3,5,4])[0, np.ones((3, 5), dtype=bool), :-1].shape

In [11]:
10**3**2

1000000000

In [13]:
2**-0.5**2, 2**(-0.5**2) , (2**-0.5)**2 

(0.8408964152537145, 0.8408964152537145, 0.5000000000000001)

In [14]:
np.isclose(np.ones((4, 5)), np.ones((3)))

ValueError: operands could not be broadcast together with shapes (4,5) (3,) 

In [15]:
-1**2

-1

In [18]:
np.linspace(0,1,10, endpoint=True)
np.geomspace

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [21]:
~np.zeros((100,100), dtype=int)


array([[-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       ...,
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1],
       [-1, -1, -1, ..., -1, -1, -1]])

In [50]:
np.arange(120).reshape(2,3,4,5)[..., np.arange(12).reshape((3,4))<5, None, :]

array([[[[ 0,  1,  2,  3,  4]],

        [[ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14]],

        [[15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24]]],


       [[[60, 61, 62, 63, 64]],

        [[65, 66, 67, 68, 69]],

        [[70, 71, 72, 73, 74]],

        [[75, 76, 77, 78, 79]],

        [[80, 81, 82, 83, 84]]]])

In [48]:
np.arange(120).reshape(2,3,4,5)[..., np.arange(12).reshape((3,4))<5, None, :, ...].shape

IndexError: an index can only have a single ellipsis ('...')

In [49]:
np.arange(120).reshape(2,3,4,5)[..., 0,0,0,0]

array(0)

In [3]:
x = np.arange(12).reshape((3,4))
y = x[0:1:3, 1:3]
print(y.base)
y = x[..., 1:3]
print(y.base)

y = x[0, 1:3]
print(y.base)

y = x[np.ones_like(x, dtype=bool)]
print(y.base)

print(x.ravel().base)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
None
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
np.isclose